version: '3'

services:
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - pepepe:/data/db
  
  webserver:
    build: .
    ports:
      - 80:80
    volumes:
      - ./blog:/var/www/html

volumes: 
  pepepe:   